const fs = require('fs');
const path = require('path');

let code = fs.readFileSync('js/chatbot.js', 'utf8');
const existingIds = [...code.matchAll(/id:'([^']+)'/g)].map(m => m[1]);

console.log('Existing KB IDs count:', existingIds.length);
console.log('Current line count:', code.split('\n').length);

function insertBefore(marker, entries) {
  const pos = code.indexOf(marker);
  if (pos === -1) {
    console.error('Marker not found: ' + marker);
    return false;
  }
  code = code.slice(0, pos) + entries + code.slice(pos);
  return true;
}

// ============================================================================
// GROUP 1: MORE ROLEX POPULAR REFERENCES (insert before { id:'ap_general')
// ============================================================================

const rolex = `
{ id:'rolex_126710blro_oyster', kw:['GMT-Master II','Pepsi Oyster','ceramic bezel'],
  r:()=>{ ctx.brand='Rolex'; ctx.model='GMT-Master II 126710BLRO'; return t(
    \`FR: La GMT-Master II 126710BLRO est la version 2023 du legendaire chronographe bizone de Rolex, montee sur bracelet Oyster acier au lieu du Jubilee habituel. Equipee du calibre 3285 de derniere generation (70h reserve de marche, remontage automatique), cette montre 40mm propose la celebre lunette ceramique Pepsi (rouge et bleu) - symbole iconique du modele depuis 1960. L'etanche 100m WR convient aux activites nautiques. Le cadran gris avec aiguille GMT orange offre une lisibilite exceptionnelle pour les voyageurs internationaux. Production limitee, liste d'attente importante. Prix catalogue: €15,950. Successeur de l'ancienne ref 16710 avec mouvements vintage plus lents (48h). Cette version Oyster (vs Jubilee) cible les porteurs preferant un style plus sportif et viril. Collecteurs: modele de transition pendant l'ere CEL/non-CEL du mouvement 3285.\`,
    \`EN: The 2023 Rolex GMT-Master II reference 126710BLRO is the steel sports watch icon worn by pilots and traders globally, now offered on Oyster bracelet instead of the standard Jubilee. Housing the brand-new caliber 3285 (automatic, 70-hour power reserve, anti-magnetic, certified chronometer), this 40mm wristwatch features the legendary ceramic Pepsi bezel—red and blue—unchanged since 1960. Water-resistant to 100m (330 feet), suitable for recreational diving and water sports. The grey sunburst dial with orange GMT hand enables precise timekeeping across two time zones. Waiting lists at Rolex ADs stretch 2-4 years. Retail price: USD 14,800. This Oyster configuration delivers a sportier aesthetic compared to the traditional Jubilee, preferred by tool-watch enthusiasts. The 3285 movement represents a major upgrade from the 3186/3187 in vintage references—better chronometry, extended longevity, and improved anti-magnetism. Investment grade: consistent secondary market appreciation.\`
  );} },

{ id:'rolex_m126234', kw:['Datejust 36','Fluted Jubilee','steel gold'],
  r:()=>{ ctx.brand='Rolex'; ctx.model='Datejust 36 M126234'; return t(
    \`FR: Le Datejust 36 M126234 est le champion toutes categories pour la premiere montre Rolex classique, combinant elegance intemporelle et polyvalence. Cette montre 36mm en acier ou or blanc avec lunette cannele et bracelet Jubilee represente le summum du design horloger conservateur. Le mouvement calibre 3235 (70h reserve, chronometer certifie) offre fiabilite absolue. Les cadrans disponibles - bleu, gris, noir, blanc - conviennent a tous les environnements professionnels. L'etanche 100m WR suffit pour l'usage quotidien intensif. Ref M (non-Ref A) introduite en 2020 avec amortisseurs suspendus ameliores du garde-temps. Prix: €7,800 acier; €16,950 or blanc. Configuration la plus demandee par les collecteurs novices - equilibre parfait entre prix, style, et desirabilite.\`,
    \`EN: The Rolex Datejust 36 reference M126234 is the quintessential first luxury watch for discerning collectors, pairing timeless classical design with outstanding versatility. Available in steel or white gold with fluted bezel and Jubilee bracelet, this 36mm dress-sports piece suits boardroom and casual environments equally. The caliber 3235 (70-hour PR, COSC chronometer-certified) delivers exceptional accuracy and reliability—typical 5-8 second/month deviation. Dial choices span slate, blue, black, and champagne—each appropriate for formal occasions and daily wear. Water resistance: 100m (330 feet), adequate for all non-diving activities. The M-series (post-2020) features improved damping and refined dial printing. Retail: USD 7,400 steel; USD 15,450 white gold. Most recommended entry point into Rolex collecting; waitlist 1-2 years at authorized dealers.\`
  );} },

{ id:'rolex_126621', kw:['Yacht-Master 40','Everose','two tone'],
  r:()=>{ ctx.brand='Rolex'; ctx.model='Yacht-Master 40 126621'; return t(
    \`FR: Le Yacht-Master 40 126621 conjugue acier Oystersteel et or Everose Rolex en 40mm, offrant un equilibre luxueux entre robustesse et elegance. La lunette tournante unidirectionnelle balistique facilite les calculs de temps de course aux regattas. Le calibre 3235 garantit 70h de reserve de marche et une chronometrie certifiee. Le cadran chocolat caracteristique avec aiguilles Chromalight offre un rendu classique et haut de gamme. Etanche 100m, appropriee pour la navigation et les sports nautiques. Production fine: les deux-tons Rolex sont manufactures avec une precision d'ajustement superieure aux montres monocouleur. Prix: €10,450. Statut de collecteur: moins populaire que Submariner/GMT mais apprecie des aficionados de design minimaliste et de sports nautiques.\`,
    \`EN: The Rolex Yacht-Master 40 reference 126621 combines Oystersteel and rose gold (Everose) in a 40mm case, balancing sporty durability with refined luxury aesthetics. The unidirectional rotatable bezel with race-timing minute markers simplifies regatta countdown calculations. Powered by the caliber 3235 (automatic, 70-hour power reserve, chronometer-certified), this watch delivers reliability expected of professional maritime instruments. The chocolate dial with Chromalight luminosity coating evokes luxury instrument watches favored by yacht captains. Water-resistant to 100m (330 feet), suitable for recreational sailing and water activities. Two-tone manufacturing demands tighter tolerances than mono-metal cases—visible in superior fit/finish. Retail: USD 9,500. Collecting perspective: less iconic than Submariner/GMT-Master II, but cherished by minimalist collectors and nautical enthusiasts for understated elegance.\`
  );} },

{ id:'rolex_226570_white', kw:['Explorer II','White Dial','42mm'],
  r:()=>{ ctx.brand='Rolex'; ctx.model='Explorer II 226570 White'; return t(
    \`FR: Le nouvel Explorer II 226570 cadran blanc (2021) marque la renaissance d'une legende Rolex, offrant une montre d'expedition authentique en 42mm acier. Equipee du calibre 3285 derniere generation (70h reserve, remontage chronometer), cette montre incarne l'heritage Steve McQueen et des expeditions polaires. Le cadran blanc pur avec aiguille GMT orange et index appliques confere une lisiblite polaire absolue. La fonction 24h aide les explorateurs a mesurer jours et nuits aux latitudes extremes. L'etanche 100m suffit pour l'expedition en montagne et forages arktiques. Prix: €6,200. Successeur du 216570, cette version 3285 beneficie d'une chronometrie superieure et d'une anti-magnetisme amelioree (precision montre de poche). Tres demandee par les collecteurs sport-modernes.\`,
    \`EN: The 2021 Explorer II reference 226570 with white dial resurrects Rolex's expedition-watch heritage in a robust 42mm steel case. Powered by the caliber 3285 (automatic, 70-hour power reserve, COSC chronometer-certified), this tool watch honors the legacy of polar expeditions and Steve McQueen's legendary adventures. The pure white dial with orange 24-hour GMT hand and applied indices provides exceptional readability in snow-glare conditions. The 24-hour hand assists arctic explorers in tracking day/night cycles at extreme latitudes. Water-resistant 100m (330 feet), adequate for mountaineering and polar expeditions. Retail: USD 5,625. Successor to the 216570; this 3285-powered generation achieves superior chronometric performance and enhanced magnetism resistance. Highly sought by modern sport-watch collectors.\`
  );} },

{ id:'rolex_226570_black', kw:['Explorer II','Black Dial','tool watch'],
  r:()=>{ ctx.brand='Rolex'; ctx.model='Explorer II 226570 Black'; return t(
    \`FR: La version cadran noir du meme Explorer II 226570 (2021) perpetue l'aesthetic intemporelle des montres de terrain Rolex, avec meme precision 3285 et etanche 100m WR. Le contraste entre cadran noir mate et aiguille GMT orange accentue la lisibilite dans les conditions extremes. Configuration preferee par les collecteurs apprisant une esthetique plutot militaire et tool-watch. Moins demandee que la version blanche polaire, mais appreciee des amateurs de style classique intemporel. Prix identique a la version blanche: €6,200. Authentique instrument d'expedition moderne.\`,
    \`EN: The black dial variant of the 2021 Explorer II 226570 maintains Rolex's timeless tool-watch aesthetic, retaining the same caliber 3285 movement and 100m water resistance. The contrast between matte black dial and orange 24-hour GMT hand enhances legibility in harsh field conditions. Preferred by collectors embracing military minimalism and pure tool-watch philosophy. Less pursued than the white Polar variant but appreciated by classicists valuing understated durability. Retail price identical: USD 5,625. A genuine modern expedition instrument without compromise.\`
  );} },

{ id:'rolex_326235', kw:['Sky-Dweller','Everose','annual calendar'],
  r:()=>{ ctx.brand='Rolex'; ctx.model='Sky-Dweller 326235'; return t(
    \`FR: Le Sky-Dweller 326235 en or Everose 42mm est le chef-d'oeuvre ultra-complexe de Rolex pour les pilotes et voyageurs perpetuels. Le calibre 9001 (remontage automatique, 72h reserve, 13 complications) integre un calendrier annuel ne necessitant correction qu'une fois par an. La lunette Command reglee par corone segmentee permet reglages precis du fuso horaire local et heure secondaire. Verre acrylique bombé avec cyclope retro offre charisme vintage. Etanche 100m. Prix: €39,600. Montre la plus techniquement sophistiquee de Rolex - reserve des collecteurs ultra-experts et cadres d'entreprise volant internationalement. Edition limitee annuellement.\`,
    \`EN: The Rolex Sky-Dweller reference 326235 in 42mm rose gold (Everose) represents Rolex's pinnacle horological complexity, engineered for international pilots and perpetual travelers. The in-house caliber 9001 (automatic, 72-hour power reserve, 13 complications) features an annual calendar requiring only one correction per calendar year. The Command bezel with segmented crown crown allows precise local-time and secondary-time adjustments. The domed acrylic crystal with cyclope magnifier delivers vintage charisma alongside modern legibility. Water-resistant to 100m (330 feet). Retail: USD 36,000. Rolex's most technically sophisticated production watch—reserved for expert collectors and international executives. Annual limited production.\`
  );} },

{ id:'rolex_50509', kw:['Cellini Date','white gold','dress watch'],
  r:()=>{ ctx.brand='Rolex'; ctx.model='Cellini Date 50509'; return t(
    \`FR: Le Cellini Date 50509 39mm en or blanc Rolex incarne le summum de la montre de ceremonie moderne, avec chaste lunette cannele doublee et boitier lisse reminiscent des montres anciennes. Le calibre 3165 (remontage automatique, 48h reserve) assure precision et fiabilite. Double couronne (une pour date, une pour remontage) offre interface sophistiquee. Etanche 50m - une limite deliberee affirm ant son role comme montre de salon exclusif plutot que quotidienne. Cadran blanc ou noir argent. Prix: €17,500. Rarity absolue dans les portfolios collecteurs Rolex - moins de 2% des montres Rolex vendues. Appreciation historique exceptionnelle.\`,
    \`EN: The Rolex Cellini Date reference 50509 in 39mm white gold exemplifies modern dress-watch supremacy, with its chaste fluted bezel and polished case echoing vintage timepieces. The caliber 3165 (automatic, 48-hour power reserve) ensures reliable accuracy for formal occasions. Twin crown design (one for date-setting, one for winding) provides sophisticated operational interface. Water-resistant to 50m (164 feet)—deliberately limited to reinforce its exclusive salon-watch positioning rather than daily sports utility. Dial choices: white or silver. Retail: USD 15,950. Absolute rarity within Rolex collector portfolios—fewer than 2% of Rolex annual production. Exceptional historical appreciation trajectory.\`
  );} },

{ id:'rolex_m126710blnr_oyster', kw:['GMT-Master II','Batman','Oyster bracelet'],
  r:()=>{ ctx.brand='Rolex'; ctx.model='GMT-Master II M126710BLNR'; return t(
    \`FR: Le GMT-Master II M126710BLNR sur bracelet Oyster (2023) est la version sportive du mythique Batman noir-bleu, offrant meme calibre 3285 et ceramique lunette mais avec cadran noir plutot que gris. Montee sur bracelet Oyster acier (au lieu du Jubilee standard), cette montre 40mm offre esthetique more robuste et masculine. Reserve 70h, etanche 100m WR. Configuration moins demandee que la version 126710BLRO grise mais appriciee des amateurs de "tool watch" trop purs. Prix: €15,950. Meme famille de references que le Pepsi mais avec colorimetrie inverse pour des collecteurs priorisant une presentation noir-sportive.\`,
    \`EN: The 2023 GMT-Master II reference M126710BLNR on Oyster bracelet delivers the iconic Batman black-and-blue ceramic bezel in a sportier presentation. Identical caliber 3285 (70-hour power reserve, chronometer-certified) and same 100m water resistance as the Pepsi variant, but with a contrasting black dial. Mounted on Oyster bracelet (rather than standard Jubilee), this 40mm sports watch conveys heightened masculinity and tool-watch ruggedness. Less pursued than the grey-dial Pepsi but favored by pure-sport collectors prioritizing sinister aesthetics. Retail: USD 14,800. Sibling to the Pepsi within the contemporary GMT lineage—preferred by collectors seeking inverted colorimetry.\`
  );} },
`;

// ============================================================================
// GROUP 2: MORE AP REFERENCES (insert before { id:'patek_general')
// ============================================================================

const ap = `
{ id:'ap_26470io', kw:['Offshore 42mm','ceramic titanium','dive watch'],
  r:()=>{ ctx.brand='Audemars Piguet'; ctx.model='Offshore 26470IO'; return t(
    \`FR: L'Offshore 26470IO 2024 conjugue ceramique noire et titane ultra-legers en 42mm pour une montre de plongee sport-luxe absolue. Le calibre 2385 (remontage automatique, 40h reserve) offre une precision acceptable. Le design futuriste avec boitier ceramique/titane et lunette tournante unidirectionnelle rappelle l'heritage Offshore depuis 1993. Etanche 300m pour la plongee recreational et professionnelle. Avec cassette "Chronograph" - complications additionnelles mesures pour expeditions. La riche palette ceramique /titane (poids leger) attire les collecteurs modernes cherchant techno-materialite. Prix: €32,000. Production limitee annuellement.\`,
    \`EN: The 2024 Audemars Piguet Offshore reference 26470IO unites black ceramic and ultra-light titanium in a 42mm sports-diving package combining functionality with avant-garde aesthetics. The caliber 2385 (automatic, 40-hour power reserve, chronometer-certified) delivers solid chronometric performance. The futuristic case design—ceramic/titanium—and unidirectional rotating bezel echo the Offshore legacy since 1993. Water-resistant to 300m (984 feet) for recreational and professional diving. Available with integrated chronograph complication for expedition timing. The ceramic/titanium palette appeals to contemporary collectors valuing material innovation and reduced weight. Retail: USD 29,000. Annual limited production.\`
  );} },

{ id:'ap_15530st', kw:['Royal Oak 41mm','self-winding','newest generation'],
  r:()=>{ ctx.brand='Audemars Piguet'; ctx.model='Royal Oak 15530ST'; return t(
    \`FR: Le Royal Oak 15530ST acier 41mm est la montre de prestige absolute d'AP, combinant design octagonale avant-gardiste (depuis 1972) avec precision horlogere contemporaine. Le calibre 4302/4309 (remontage automatique, 70h reserve, chronometer) offre chronometrie exceptionnelle et resistance magnetique renforcee. Le bracelet integre fond taper est iconique - reconnaissable instantanement. Etanche 50m pour usage quotidien raffiné. Cadrans options: bleu, noir, blanc, gris gradient. Prix: €26,500. Montre de retraite pour collecteurs avertis - symbol absolu du luxury sports-watch. Liste d'attente 3-5 ans chez revendeurs authorises.\`,
    \`EN: The Audemars Piguet Royal Oak 15530ST in 41mm steel is the ultimate prestige sports watch, melding the avant-garde octagonal case (since 1972) with contemporary watchmaking precision. The caliber 4302/4309 (automatic, 70-hour power reserve, chronometer-certified) achieves exceptional accuracy and reinforced magnetic resistance. The integrated tapered bracelet is instantly iconic—recognized globally as a status symbol. Water-resistant 50m (164 feet) for refined daily wear. Dial options: blue, black, white, grey gradient. Retail: USD 24,000. The retirement watch for expert collectors—absolute symbol of luxury sports-watch supremacy. Waiting lists: 3-5 years at authorized dealers.\`
  );} },

{ id:'ap_26231st_glass', kw:['Offshore Chronograph','sapphire caseback','exhibition'],
  r:()=>{ ctx.brand='Audemars Piguet'; ctx.model='Offshore Chronograph 26231ST'; return t(
    \`FR: L'Offshore Chronograph 26231ST 42mm avec fond saphir expose le calibre 3126/3840 (chronographe integre) a travers le verre, offrant theatre horloger pour collecteurs techno-curieux. Acier massif, lunette tournante unidirectionnelle ceramique noire, compteurs de chronographe visibles cadran. L'exhibition caseback revele balancier oscillant et ressorts en spirale - element essentiel pour appreciateurs du mecanisme. Etanche 300m pour plongee professionnelle. Remontage automatique, 50h reserve. Prix: €29,500. Moins demandee que la version à fond lisse (plus cher en fabrication) mais appriciee des collecteurs horlogers sinceres.\`,
    \`EN: The Audemars Piguet Offshore Chronograph reference 26231ST in 42mm steel with exhibition caseback exposes the integrated chronograph caliber 3126/3840 through sapphire crystal, offering horological theatre for technically curious collectors. Solid steel case, ceramic unidirectional rotating bezel, chronograph counters integrated on dial. The exhibition case-back reveals the oscillating balance wheel and spiral springs—essential for mechanism aficionados. Water-resistant to 300m (984 feet) for professional diving. Automatic winding, 50-hour power reserve. Retail: USD 26,800. Less pursued than closed case-back variants (more costly fabrication) but valued by serious horological collectors.\`
  );} },

{ id:'ap_77351or', kw:['Royal Oak Ladies','34mm rose gold','pave diamond'],
  r:()=>{ ctx.brand='Audemars Piguet'; ctx.model='Royal Oak Ladies 77351OR'; return t(
    \`FR: Le Royal Oak Dames 77351OR 34mm or rose avec lunette pavee de diamants offre luxe feminin intemporel a travers l'iconic octagon. Calibre 2061 (remontage manuel, 40h reserve) assure mouvement visible et traditionnel. Cadran blanc ou gris. Etanche 50m. La pavage diamant lunette cible collectrices nantis cherchant elegance sportive avec prestige gemologique. Production tres limitee. Prix: €42,000+. Apprieciation constante due a l'acier or rose et diamants naturels.\`,
    \`EN: The Audemars Piguet Royal Oak Ladies reference 77351OR in 34mm rose gold with pave diamond-set bezel delivers timeless feminine luxury through the iconic octagonal case. The caliber 2061 (manual winding, 40-hour power reserve) offers visible traditional mechanism—appealing to purists valuing craftsmanship transparency. Dial options: white or grey. Water-resistant 50m (164 feet). The diamond pavé bezel targets affluent collectors seeking sports-watch elegance combined with gemological prestige. Very limited production. Retail: USD 38,000+. Consistent appreciation driven by rose gold and natural diamond scarcity.\`
  );} },

{ id:'ap_15500st_grey', kw:['Royal Oak 41mm','grey dial','modern classic'],
  r:()=>{ ctx.brand='Audemars Piguet'; ctx.model='Royal Oak 15500ST Grey'; return t(
    \`FR: Le Royal Oak 15500ST 41mm cadran gris gradient est la configuration la plus demandee actuellement, combinant subtilité colorimetrique avec esthétique moderne. Meme calibre 4302 (70h reserve, chronometer certifie) et bracelet integré taper. Le cadran gris gradient offre transitions subtiles du gris clair au fonce, revelant la qualité de finition AP supreme. Etanche 50m. Prix: €26,500. Configuration reine pour collecteurs novices cherchant Royal Oak authentic mais avec presentation contemporaine. Moins de liste d'attente que le noir mais toujours 2-3 ans chez revendeurs.\`,
    \`EN: The Audemars Piguet Royal Oak 15500ST in 41mm with grey gradient dial is currently the most sought configuration, pairing subtle colorimetry with contemporary aesthetics. Same caliber 4302 (70-hour power reserve, chronometer-certified) and integrated tapered bracelet. The grey gradient dial reveals subtle light-to-dark transitions—showcasing AP's supreme finishing quality. Water-resistant 50m (164 feet). Retail: USD 24,000. The gold-standard entry configuration for novice collectors seeking authentic Royal Oak with modern presentation. Shorter waiting lists than black dial but still 2-3 years at authorized dealers.\`
  );} },

{ id:'ap_26574or_blue', kw:['Perpetual Calendar rose gold','blue dial','collector holy grail'],
  r:()=>{ ctx.brand='Audemars Piguet'; ctx.model='Perpetual Calendar 26574OR'; return t(
    \`FR: Le Perpetual Calendar 26574OR 41mm or rose cadran bleu laque est le graal des collecteurs AP, conjuguant 6 complications horlogeres majeures (perpetuel calendar, chronographe flyback, GMT, reserve de marche) en un seul mecanisme. Le calibre 2120/2800 (remontage automatique, 68h reserve) integre balancier a couronne et spiral Parachrom pour chrononmetrie exceptionnelle. Cadran bleu laque lisse confere elegance intemporelle. Etanche 50m. Production extremement limitee - moins de 50 pieces par an. Prix: €325,000. Appreciation rare > 100% a la revente. Montre d'exception pour collecteurs multi-milliardaires.\`,
    \`EN: The Audemars Piguet Perpetual Calendar reference 26574OR in 41mm rose gold with lacquered blue dial is the holy grail for AP collectors, integrating six major horological complications (perpetual calendar, flyback chronograph, GMT, moonphase, power-reserve, date) into a unified mechanism. The caliber 2120/2800 (automatic, 68-hour power reserve) features crown balance and Parachrom spiral for exceptional chronometry resistant to gravity and magnetism. The smooth lacquered blue dial conveys timeless elegance. Water-resistant 50m (164 feet). Extremely limited production—fewer than 50 pieces annually worldwide. Retail: USD 295,000. Rare secondary-market appreciation exceeds 100%. Exceptional timepiece for ultra-high-net-worth collectors only.\`
  );} },
`;

// ============================================================================
// GROUP 3: MORE PATEK REFERENCES (insert before { id:'rm_general')
// ============================================================================

const patek = `
{ id:'patek_5711_1r', kw:['Nautilus rose gold','rare variant','40mm'],
  r:()=>{ ctx.brand='Patek Philippe'; ctx.model='Nautilus 5711/1R'; return t(
    \`FR: Le Nautilus 5711/1R rose gold 40mm est la variation rarement produite du chef-d'oeuvre 1976, combinant boitier integre iconic avec precious metal prestige. Cadran bleu ou argent. Le calibre 324 SC (remontage automatique, 45h reserve, chronometer) offre fiabilite legendaire. Lunette rotative tournante. Etanche 120m. Production excessivement limitee - moins de 5 pieces par annee. Prix pre-owned €350,000+. Rarite absolue. Appreciation secondaire constante a causa de materialite or rose et limite productivite.\`,
    \`EN: The Patek Philippe Nautilus reference 5711/1R in 40mm rose gold is the rarely-produced variant of the legendary 1976 integrated sports watch, combining the iconic case geometry with precious metal prestige. Dial options: blue or silver. The caliber 324 SC (automatic, 45-hour power reserve, chronometer-certified) delivers legendary reliability. Rotating bezel, integral bracelet. Water-resistant 120m (394 feet). Excessively limited production—fewer than 5 pieces annually. Pre-owned retail: USD 320,000+. Absolute rarity. Consistent secondary appreciation driven by rose gold scarcity and production constraints.\`
  );} },

{ id:'patek_5167r', kw:['Aquanaut rose gold','composite strap','40mm travel'],
  r:()=>{ ctx.brand='Patek Philippe'; ctx.model='Aquanaut 5167R'; return t(
    \`FR: L'Aquanaut 5167R rose gold 40mm with composite leather/rubber strap offre polyvalence luxe pour voyageurs affirmes, combinant boitier unique courbe de Patek avec precious metal. Le calibre 324 SC (remontage automatique, 45h reserve) assure chronometrie fiable. Cadran bleu marine, noir, ou blanc. Etanche 120m pour usage quotidien et snorkeling occasion nel. Lunette tournante unidirectionnelle. Bracelet composite Patek combine elasticite caoutchouc avec elegance cuir - ideale pour voyage global. Prix: €28,500. Moins demandee que Nautilus mais appriciee des voyageurs globaux.\`,
    \`EN: The Patek Philippe Aquanaut reference 5167R in 40mm rose gold with composite leather/rubber strap delivers luxury versatility for discerning travelers, combining Patek's unique curved case with precious metal dignity. The caliber 324 SC (automatic, 45-hour power reserve, chronometer-certified) ensures reliable chronometry. Dial options: navy, black, or white. Water-resistant 120m (394 feet) for daily use and occasional snorkeling. Unidirectional rotating bezel. The composite Patek strap blends rubber elasticity with leather refinement—ideal for global travel. Retail: USD 26,000. Less iconic than Nautilus but cherished by international travelers.\`
  );} },

{ id:'patek_5131j', kw:['World Time cloisonne','enamel dial','yellow gold'],
  r:()=>{ ctx.brand='Patek Philippe'; ctx.model='World Time 5131J'; return t(
    \`FR: Le World Time 5131J or jaune 39.5mm with cloisonne enamel cadran peint a main est le chef-d'oeuvre ultime pour collecteurs d'art horloger, affichant 24 fuseaux horaires sur lunette tournante avec cadran enamel cloisonne custom. Chaque cadran unique est oeuvre d'art appliquee - peint a main par artisans enamel Patek specialises. Calibre 240 HU (remontage manuel, 48h reserve). Production unidirectionnelle: UNE SEULE piece par client commande, design custom. Prix: €180,000+. Delai livraison 3-5 ans. Appreciation historique exceptionnelle > 200% post-acquisition. Montre pour collecteurs ultra-passionnes.\`,
    \`EN: The Patek Philippe World Time reference 5131J in yellow gold with 39.5mm case and hand-painted cloisonné enamel dial is the ultimate horological art-object, displaying 24 time zones on rotating bezel with custom cloisonné enamel dial. Each dial is a unique artwork—hand-painted by Patek's specialized enamel artisans using centuries-old techniques. The caliber 240 HU (manual winding, 48-hour power reserve) powers this masterpiece. Production model: ONE piece per client order with custom design specification. Retail: USD 165,000+. Delivery wait: 3-5 years. Historical appreciation exceeds 200% post-acquisition. Reserved for ultra-passionate collectors only.\`
  );} },

{ id:'patek_5327g', kw:['Perpetual Calendar','white gold','lacquered blue'],
  r:()=>{ ctx.brand='Patek Philippe'; ctx.model='Perpetual Calendar 5327G'; return t(
    \`FR: Le Perpetual Calendar 5327G or blanc 39.5mm cadran bleu laque is le Perpetual Calendar entry-level supreme de Patek, offrant 6 complications (perpetuel, chronographe, reserve, date, jour, mois) sans chronographe flyback complexe de la ref 5327. Calibre 240 Q (remontage manuel, 48h) integre mecanisme perpetuel ingenieux ne necessitant correction que le 1er mars 2100. Cadran bleu laque lisse avec index appliques offre elegance intemporelle. Etanche 50m. Prix: €110,000. Production limitee a ~100 pieces par annee. Appreciation: 15-25% par annee a causa de specifications perpetuelles.\`,
    \`EN: The Patek Philippe Perpetual Calendar reference 5327G in 39.5mm white gold with lacquered blue dial is Patek's supreme perpetual-calendar entry point, integrating six complications (perpetual calendar, moonphase, power reserve, date, day, month) without the complex flyback chronograph of higher references. The caliber 240 Q (manual winding, 48-hour power reserve) incorporates Patek's ingenious perpetual mechanism requiring correction only on March 1, 2100. The smooth lacquered blue dial with applied indices conveys timeless elegance. Water-resistant 50m (164 feet). Retail: USD 100,000. Limited production: ~100 pieces annually. Appreciation: 15-25% annually due to perpetual specifications.\`
  );} },

{ id:'patek_5935a', kw:['World Time Chronograph','steel latest','flyback'],
  r:()=>{ ctx.brand='Patek Philippe'; ctx.model='World Time Flyback 5935A'; return t(
    \`FR: Le World Time Flyback Chronograph 5935A acier 40.8mm est la montre de voyage plus ambitieuse de Patek, combinant chronographe flyback avec 24 fuseaux horaires sur lunette. Le calibre CH 28-520 HU (remontage automatique, 55h reserve) intègre mecanisme chronographe complexe base colonne avec fonction flyback. Deux compteurs chrono cadran offrent lectures temporelle sophistiquees. Boitier acier robust mais luxe. Etanche 100m pour usage maritime. Prix: €42,000. Montre moderne pour cadres internationaux cherchant timing precision globale.\`,
    \`EN: The Patek Philippe World Time Flyback Chronograph reference 5935A in 40.8mm steel is Patek's most ambitious travel chronograph, combining flyback chronograph with 24-hour time-zone display on rotating bezel. The caliber CH 28-520 HU (automatic, 55-hour power reserve) integrates complex column-wheel chronograph with integrated flyback function. Twin subdial chronograph counters enable sophisticated temporal readings. Steel case balances robustness with refined aesthetic. Water-resistant 100m (330 feet) for maritime use. Retail: USD 38,000. Modern timepiece for international executives seeking global timing precision.\`
  );} },

{ id:'patek_5180_1r', kw:['Nautilus Skeleton','rose gold','openworked'],
  r:()=>{ ctx.brand='Patek Philippe'; ctx.model='Nautilus Skeleton 5180/1R'; return t(
    \`FR: Le Nautilus Skeleton 5180/1R or rose 40mm expose le calibre 240 SQU (remontage manuel, 48h reserve) a travers le verre bombé, offrant theatre horloger supreme pour collecteurs mecanisme-passionnes. Le boitier integre iconic reste massif or rose. Cadran "open" avec balancier oscillant visible et ressorts spirales creent symphony visuelle. Etanche 120m. Production excessivement limitee - moins de 10 pieces par annee. Prix: €250,000+. Montre showpiece pour collecteurs ultra-haut-filet.\`,
    \`EN: The Patek Philippe Nautilus Skeleton reference 5180/1R in 40mm rose gold exposes the caliber 240 SQU (manual winding, 48-hour power reserve) through domed sapphire crystal, offering supreme horological theatre for mechanism-passionate collectors. The iconic integrated case remains substantial rose gold. The open dial with visible oscillating balance wheel and spiral springs creates visual symphony. Water-resistant 120m (394 feet). Excessively limited production—fewer than 10 pieces annually. Retail: USD 230,000+. Showpiece timepiece for ultra-high-net-worth collectors.\`
  );} },
`;

// ============================================================================
// GROUP 4: WATCH EDUCATION & BUYING GUIDE ENTRIES (insert before { id:'fallback')
// ============================================================================

const guides = `
{ id:'guide_first_rolex', kw:['first Rolex','which model','beginner guide'],
  r:()=>{ ctx.brand='Rolex'; ctx.type='Educational'; return t(
    \`FR: Choisir sa premiere Rolex est une decision majeure qui determine la trajectoire collectrice. Les trois candidats principaux: Submariner (tool watch legendaire, 100+ annees heritage, icone James Bond), Datejust (elegance classique pour tous contextes, premiere vraie montre de luxe), Oyster Perpetual (entree budget, acier seul, excellent starter). Submariner convient aux collecteurs sport-tech recherchant polyvalence eau/montagne. Datejust cible cadres professionnels elegant, differentes tailles 36/41/42mm, configurable acier/or selon budget. Oyster Perpetual offre qualité Rolex absolute au prix minimum - excellente introduction sans compromis horloger. Listes d'attente: Submariner 3-5 ans, Datejust 1-3 ans, Oyster Perpetual moins d'1 an généralement. Budget acier: €4,500-€8,000. Budget or: €15,000-€35,000+. Secret: les couleurs cadran (bleu, noir, argent) affectent desirabilitee et listes d'attente significativement. Submariner noir plus demande que bleu. Datejust gris très recherche actuellement. Conseil: debuter avec montre vous voulant vraiment porter quotidiennement, pas investissement pur - appreciation vient naturellement avec temps.\`,
    \`EN: Selecting your first Rolex represents a pivotal decision shaping your entire collecting trajectory. Three primary candidates: Submariner (legendary tool-watch, 100+ year heritage, James Bond icon), Datejust (classical elegance across all contexts, first true luxury watch), Oyster Perpetual (budget entry point, steel-only, exceptional starter). Submariner suits sport-tech collectors seeking water/mountain versatility. Datejust targets elegant professionals; multiple sizes (36/41/42mm) and material options (steel/gold) match budgets. Oyster Perpetual delivers absolute Rolex quality at minimum price point—excellent introduction without horological compromise. Waiting lists: Submariner 3-5 years, Datejust 1-3 years, Oyster Perpetual typically under 1 year. Budget steel: USD 4,000-USD 7,500. Budget gold: USD 14,000-USD 32,000+. Secret: dial colors (blue, black, silver) significantly affect desirability and waiting times. Submariner black more pursued than blue. Datejust grey highly sought currently. Advice: begin with a watch you genuinely want wearing daily, not pure investment—appreciation follows naturally over time.\`
  );} },

{ id:'guide_first_ap', kw:['first Audemars Piguet','Royal Oak','which reference'],
  r:()=>{ ctx.brand='Audemars Piguet'; ctx.type='Educational'; return t(
    \`FR: La premiere Audemars Piguet devrait etre Royal Oak 15500ST acier (champion absolut depuis 2012), pas Offshore (trop sport), pas Code 11.59 (divisif design). Royal Oak 15500ST 41mm offre octagon legendaire depuis 1972, calibre 4302 ultra-fiable (70h reserve, chronometer), bracelet integré iconic reconnaissable instantanement globalement. Size 41mm domine actuellement - 36mm moins demande. Cadrans: bleu gradient TRES recherche actuellement, noir solide, gris gradient moderne. Liste d'attente terrible: 3-5 ans generalement meme chez revendeurs riches. Secret: gris et bleu moins demandes que noir - tenter ces couleurs pour liste d'attente courte. Offshore attire collecteurs "statement sportif" cherchant esthetique moderne extreme - moins heritage, plus techno-materiel. Code 11.59 propose design futuriste controversé - certains adorent, certains detestent (eviter si vous ne etes pas tres convaincu). Budget Royal Oak 15500ST acier: €26,500. Conseil: Royal Oak est montre "lifetime acquisition" - achetez le model et la couleur que vous aimerez porter TOUJOURS, pas speculation.\`,
    \`EN: Your first Audemars Piguet should be Royal Oak 15500ST steel (absolute champion since 2012 redesign), not Offshore (too aggressively sporty), not Code 11.59 (divisive design). Royal Oak 15500ST 41mm showcases the legendary octagon since 1972, relies on ultra-reliable caliber 4302 (70-hour PR, chronometer), and features the iconic integrated bracelet recognized globally instantly. The 41mm size dominates currently—36mm less pursued. Dials: blue gradient highly sought currently, black solid classic, grey gradient contemporary-modern. Waiting lists brutal: 3-5 years typically even among wealthy dealers. Secret: grey and blue dials shorter waiting lists than black—try these for quicker acquisition. Offshore appeals to "statement sport" collectors seeking extreme modern aesthetics—less heritage, more techno-material innovation. Code 11.59 offers controversial futuristic design—some love, many despise (avoid unless thoroughly convinced). Budget Royal Oak 15500ST steel: USD 24,000. Advice: Royal Oak is lifetime-ownership watch—buy the size/color you'll wear forever, not speculation.\`
  );} },

{ id:'guide_first_patek', kw:['first Patek Philippe','Nautilus wait','Aquanaut entry'],
  r:()=>{ ctx.brand='Patek Philippe'; ctx.type='Educational'; return t(
    \`FR: Premiere Patek Philippe pose dilemma budget: Nautilus 5711A acier (montre reine iconique mais 5-8 ans liste d'attente, €38,500+) vs Aquanaut 5167A acier (plus accessible, 2-3 ans attente, €18,500) vs Calatrava 5226G (elegance formelle, moins demande, €16,500). Nautilus: symbol prestige absolut, integre depuis 1976, reste tres demande. Aquanaut: polyvalence excellente, bracelet composite unique, moins heritage que Nautilus mais plus "cool" design moderne. Calatrava: montre formelle classique, appreciation historique solide, zero liste d'attente generalement - achetez immediatement si possible. Budget: Aquanaut €18,500 (moins attente), Nautilus €38,500+ (TRES attente), Calatrava €16,500 (pas d'attente). Secret intelligence: Calatrava offre meilleur rapport qualite/attente - montre magnifique sans frustration listem d'attente eternelle. Certains collecteurs commencent Calatrava, puis Aquanaut, puis Nautilus 10 ans apres. Conseil: eviter achat gris-market (pas de garantie, risque authentication, dealers legitimates refusent service sans papers authentiques).\`,
    \`EN: Your first Patek Philippe poses a budget dilemma: Nautilus 5711A steel (iconic queen watch but 5-8 year waiting list, USD 35,000+) vs Aquanaut 5167A steel (more accessible, 2-3 year wait, USD 17,000) vs Calatrava 5226G (formal elegance, minimal demand, USD 15,000). Nautilus: absolute prestige symbol, integrated since 1976, perpetually in demand. Aquanaut: excellent versatility, unique composite bracelet, less heritage than Nautilus but more "cool" modern design. Calatrava: classical formal watch, solid appreciation history, zero waiting list typically—purchase immediately if possible. Budget: Aquanaut USD 17,000 (moderate wait), Nautilus USD 35,000+ (EXTREME wait), Calatrava USD 15,000 (no wait). Secret intelligence: Calatrava offers best quality/wait ratio—magnificent watch without eternal waiting frustration. Some collectors begin Calatrava, then Aquanaut, then Nautilus 10 years later. Advice: avoid grey-market purchase (no warranty, authentication risk, legitimate dealers refuse service without authentic papers).\`
  );} },

{ id:'guide_investment', kw:['watches investment','value retention','secondary market'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Les montres de luxe comme investissement: realite objective. Montres acier sports Rolex (Submariner, GMT-Master II, Datejust) apprecient 10-15% annuellement quand neuves, se stabilisent puis apprecient 5-8% long-terme. Raison: demande outrageous superieure a production limitee Rolex deliberee. Autres marques (Omega, Tudor) ne retiennent pas valeur steel - Rolex seul. Patek Philippe: appreciation exceptionnelle 15-30% annuellement pour Nautilus/Aquanaut, plus haute pour Perpetual Calendar/complications rares. Raison: manufacturing ultra-limitee et heritage perpetuel. Audemars Piguet: appreciation 8-15% annuellement pour Royal Oak, moins predictable que Patek mais plus que Rolex acier. Richard Mille: appreciation speculative 20%+ mais extremement volatile, requier expertise. RISQUES MAJEURS: 1) Marche correction cyclique possible; 2) Nouvelles productions peuvent surtout inonder grey-market, deprimer valeurs; 3) Services coûteux (€3,000-€8,000 Rolex) impactent ownership total-cost; 4) Authentification faux montres en explosion. CONSEIL: Acheter montre que vous porterez quotidiennement PLUS appreciation naturelle - jamais speculer pur. Montres conservees dans boite sans port == destruction lente valeur (oxydation, batterie, mecanisme rouille).\`,
    \`EN: Luxury watches as investment: objective reality. Rolex steel sports watches (Submariner, GMT-Master II, Datejust) appreciate 10-15% annually when new, stabilize, then appreciate 5-8% long-term. Reason: outrageous demand exceeds Rolex's deliberately limited production. Other brands (Omega, Tudor) don't retain steel value—Rolex alone dominates. Patek Philippe: exceptional appreciation 15-30% annually for Nautilus/Aquanaut, higher for Perpetual Calendar/rare complications. Reason: ultra-limited manufacturing and perpetual heritage prestige. Audemars Piguet: 8-15% annual appreciation for Royal Oak, less predictable than Patek but higher than Rolex steel. Richard Mille: speculative appreciation 20%+ but extremely volatile, requires expertise. MAJOR RISKS: 1) Market correction possible cyclically; 2) New productions flooding grey-market may depress values; 3) Service costs (USD 2,700-USD 7,300 Rolex) impact total ownership cost; 4) Counterfeit authentication explosively increasing. ADVICE: Buy watches you'll wear daily PLUS natural appreciation—never pure speculation. Watches preserved in boxes unworn = slow value destruction (oxidation, battery, mechanism rust).\`
  );} },

{ id:'guide_steel_vs_gold', kw:['steel vs gold watches','value retention','daily wear'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Acier vs or: le dilemme fondamental du collecteur. ACIER: resistance rayures inferieure (visible avec le temps), maintenance aisee, port quotidien sans culpabilite, appreciation value bonne (Rolex steel Submariner +10-15% annuellement), prix 50% moins couteux. Or jaune/rose: resistance rayures superieure (or plus mou = patine naturelle plutot que rayures nettes), maintenance intensive (polissage tous les 5 ans ~€800), port quotidien difficile (peur d'endommager prestige metal), appreciation value speculative (depend materialite or spot + demande). Or blanc: version "compromis" - resistance intermediate, maintenance moderate. VERDICT PRATIQUE: Acier ideal pour collector novice et sport-usage. Or convient collecteur expert pret entretien obsessif et port occasional formel. Rolex acier Submariner: €6,800 neuf, €8,500-€11,000 preowned 5-6 ans. Rolex or jaune Submariner: €32,000 neuf, €35,000-€45,000 preowned (appreciation limitee car or spot). SECRET: or blanc Rolex sous-evalue - moins demande que or jaune mais quality identique. Bonne opportunite acquisition.\`,
    \`EN: Steel vs gold: the fundamental collector dilemma. STEEL: lower scratch resistance (visible over time), easy maintenance, daily wear without guilt, good value appreciation (Rolex steel Submariner +10-15% annually), 50% cheaper. Yellow/rose gold: superior scratch resistance (gold softer = natural patina rather than visible scratches), intensive maintenance (polishing every 5 years ~USD 700), difficult daily wear (fear of damaging precious-metal prestige), speculative appreciation (depends on gold spot price + demand). White gold: "compromise" version—intermediate resistance, moderate maintenance. PRACTICAL VERDICT: Steel ideal for novice collectors and sport usage. Gold suits expert collectors ready for obsessive maintenance and formal-occasional wear. Rolex steel Submariner: USD 6,200 new, USD 7,700-USD 10,000 pre-owned 5-6 years. Rolex yellow-gold Submariner: USD 29,000 new, USD 32,000-USD 41,000 pre-owned (limited appreciation as gold spot-dependent). SECRET: Rolex white gold undervalued—less pursued than yellow gold but identical quality. Good acquisition opportunity.\`
  );} },

{ id:'guide_automatic_vs_quartz', kw:['automatic movement','quartz watch','mechanical vs battery'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Mouvements automatiques vs quartz: la philosophie horlogere diverge radicalement. AUTOMATIQUE (remontage automatique): ressort moteur alimente oscillation balancier (frequence 28,800 vibrations/heure typiquement), precision typique 5-15 secondes/mois, reserve marche 40-72h selon calibre, necessite remontage manuel occasionnel si port discontinu, maintenance service tous 5-10 ans (~€2,000-€5,000), appreciation prestige collecteur (mecanisme visible = art horloger), vibration tactile poignee confere sensation authentique "mecanisme vivant". Rolex utilise automatique exclusivement. QUARTZ (batterie): oscillateur quartz frequence 32,768 Hz produit precision exceptionnelle 5-10 secondes/ANNEE, batterie remplacement ~€20-€50 tous 2-3 ans, zero maintenance horlogere, legere, economique, precise MAIS perception prestige inferieure (quartz = industriel, pas art). Seiko/Omega Seamaster proposent quartz. VERDICT: automatique pour collecteurs appriant mecanisme et heritage; quartz pour pragmatiques precision-prioritaires. Rolex refuse quartz volontairement - decision marketing prestige.\`,
    \`EN: Automatic vs quartz movements: radically divergent horological philosophies. AUTOMATIC (self-winding): mainspring powers oscillating balance wheel (typically 28,800 vibrations per hour), typical accuracy 5-15 seconds per month, power reserve 40-72 hours depending on caliber, requires occasional manual winding if worn discontinuously, service maintenance every 5-10 years (~USD 1,800-USD 4,500), collector prestige appreciation (visible mechanism = horological art), tactile vibration on wrist conveys genuine "living mechanism" sensation. Rolex uses automatic exclusively. QUARTZ (battery-powered): quartz oscillator at 32,768 Hz frequency produces exceptional accuracy 5-10 seconds per YEAR, battery replacement ~USD 15-USD 40 every 2-3 years, zero horological maintenance, light, economical, supremely precise BUT lower prestige perception (quartz = industrial, not art). Seiko/Omega Seamaster offer quartz alternatives. VERDICT: automatic for collectors valuing mechanism and heritage; quartz for pragmatists prioritizing accuracy. Rolex deliberately refuses quartz—intentional prestige marketing decision.\`
  );} },

{ id:'guide_chronometer', kw:['COSC chronometer','Patek seal','certification standards'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Certification chronographe COSC vs Patek Seal: deux standards d'excellence divergents. COSC (Controle Officiel Suisse des Chronomètres): certification suisse independante testant precision mouvement sur 15 jours en differentes positions/temperatures. Precision cible COSC: -4/+6 secondes/jour (exceptionnellement strict comparé normal horlogerie). Rolex, Patek Philippe, Audemars Piguet obtiennent certification COSC de serie - c'est passage obligatoire. Prestige moderé: COSC standard luxe, pas exceptional. PATEK SEAL: certification Patek propriétaire infiniment plus exigeante que COSC - teste mouvement 1000+ heures avec precision cible -3/+2 secondes/jour (quasi-impossible). Seules montres Patek Philippe remplissent Patek Seal - marketing prestige maison. Precision atteinte: exceptionnelle, vieillissement mouvement minimal. Grand horloger comme Lange aussi utilise certification propriétaire (Lange Certificate). VERDICT: COSC certifie = qualité excellent (standard minimum Rolex/Patek); Patek Seal = qualité exceptionnelle (prestige supremum). Lors achat, verifier certification est standard de controle qualite - montre sans certification = red-flag possible faux.\`,
    \`EN: COSC Chronometer certification vs Patek Seal: two divergent excellence standards. COSC (Controle Officiel Suisse des Chronomètres): independent Swiss certification testing movement accuracy over 15 days across different positions/temperatures. COSC accuracy target: -4/+6 seconds per day (exceptionally strict versus typical horology). Rolex, Patek Philippe, Audemars Piguet achieve COSC certification standard—mandatory passage. Prestige moderate: COSC standard luxury, not exceptional. PATEK SEAL: Patek proprietary certification infinitely more demanding than COSC—tests movement 1000+ hours targeting -3/+2 seconds per day (nearly impossible). Only Patek Philippe watches achieve Patek Seal—in-house prestige marketing. Achieved precision: exceptional, movement aging minimal. Grand horlogers like A. Lange & Söhne also use proprietary certification (Lange Certificate). VERDICT: COSC certified = excellent quality (Rolex/Patek minimum standard); Patek Seal = exceptional quality (prestige maximum). When purchasing, verify certification as quality-control standard—watches without certification = possible counterfeit red-flag.\`
  );} },

{ id:'guide_water_resistance', kw:['water resistance rating','diving depth','practical meaning'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Etanche 30m/50m/100m/300m: interpretations pratiques souvent mal comprises. 30M (3 bars): FORMAL DRESS ONLY - pas d'eau du tout (respiration condensation peut penetrer). Exemples: Patek Calatrava 5226 dress watches. 50M (5 bars): RESISTANT SPLASHURE - resistance aux eclaboussures lavage mains occasionnel, JAMAIS immersion deliberee. Exemples: Patek Aquanaut 5167, Rolex Cellini dress watches. 100M (10 bars): DAILY WEAR WATER - resistance nage, douche, snorkeling superficiel (max 30 secondes immersion). Rolex Datejust, Submarine, GMT-Master II. Interpretation: 100m designé pour nage recreational et douche, PAS FOR DIVING sans formation. 300M (30 bars): RECREATIONAL DIVING - resistance dive jusqu'à ~60 metres pour divers certifies, snorkeling profond illimite. Exemples: Rolex Submariner 300m, Omega Seamaster 300m, Rolex Sea-Dweller 1000m. 1000M+ (100+ bars): PROFESSIONAL DEEP DIVING - resistance dive extreme jusqu'à 3,000+ metres. Exemples: Rolex Sea-Dweller Deepsea 3900m. CONSEIL: acheteur novice 100m suffit amplement. Certification etanche: verifier "Swiss Made" + bracelet integre implique meilleure resistance (flexion reduit etancheite).\`,
    \`EN: Water resistance 30m/50m/100m/300m: practical interpretations often misunderstood. 30M (3 bars): FORMAL DRESS ONLY—no water exposure intended (even breathing condensation can penetrate). Examples: Patek Calatrava dress watches. 50M (5 bars): SPLASH-RESISTANT—resists splashing during hand-washing occasional exposure, NEVER deliberate immersion. Examples: Patek Aquanaut, Rolex Cellini dress watches. 100M (10 bars): DAILY WEAR WATER—resistance to swimming, showering, shallow snorkeling (maximum 30 seconds immersion). Rolex Datejust, Submariner, GMT-Master II. Interpretation: 100m designed for recreational swimming and showers, NOT DIVING without certification. 300M (30 bars): RECREATIONAL DIVING—resistance to diving ~200 feet for certified divers, unlimited deep snorkeling. Examples: Rolex Submariner 300m, Omega Seamaster 300m. 1000M+ (100+ bars): PROFESSIONAL DEEP DIVING—extreme depth resistance to 9,800+ feet. Examples: Rolex Sea-Dweller Deepsea 3,900m. ADVICE: novice buyers—100m adequately sufficient. Waterproof certification: verify "Swiss Made" + integrated bracelet implies better resistance (bracelet flexing compromises seal).\`
  );} },

{ id:'guide_bracelet_guide', kw:['watch bracelet types','Oyster Jubilee','President','integrated'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Types bracelet montre: vocabulaire critique pour collecteur. OYSTER: bracelet trois-rangs acier simplifie (chainette triple) Rolex legendaire depuis 1933. Design robuste, polyvalent, moins elegant que Jubilee. Montees sur: Submariner, GMT-Master II, Sea-Dweller, Explorer, Yacht-Master. JUBILEE: bracelet neuf-rangs ornate (chainette triple croisee) Rolex depuis 1945 Datejust original. Design plus elegant, plus feminin perception, excessivement demande actuellement. Montees sur: Datejust, Day-Date, Sky-Dweller. PRESIDENT: bracelet semi-circulaire polies avec maillons profonds trois-rangees, ultra-luxe Rolex Day-Date (President watch). Finition tres raffinee. INTEGRE (Audemars Piguet): bracelet forge integralement boitier (Royal Oak depuis 1972). Design contemporain icon, zero jeu mailles, aesthetic superieur. Audemars Piguet monopole quasi-total. OYSTERFLEX: bracelet caoutchouc/metal hybrid Rolex (Yacht-Master, Sky-Dweller, Submariner Oysterflex options). Confort port, resistance chlore piscine, maintenance facile. CUIR/COMPOSITE: montages cuir ou caoutchouc (Patek Aquanaut composite, Patek Calatrava). Maintenance fastidieuse, replacement tous 5 ans (~€400-€600). CONSEIL: Jubilee plus demande = plus cher bracelets remplacement; Oyster plus compatible polyvalent.\`,
    \`EN: Watch bracelet types: critical vocabulary for collectors. OYSTER: three-row simplified steel bracelet (triple chainette) Rolex legendary since 1933. Robust design, versatile, less elegant than Jubilee. Mounted on: Submariner, GMT-Master II, Sea-Dweller, Explorer, Yacht-Master. JUBILEE: nine-row ornate bracelet (crossed triple chainette) Rolex since 1945 original Datejust. More elegant design, feminine perception, excessively sought currently. Mounted on: Datejust, Day-Date, Sky-Dweller. PRESIDENT: semi-circular polished bracelet with deep three-row links, ultra-luxury Rolex Day-Date (President watch). Exceptionally refined finishing. INTEGRATED (Audemars Piguet): bracelet forged integrally with case (Royal Oak since 1972). Contemporary iconic design, zero link play, superior aesthetics. Audemars Piguet near-total monopoly. OYSTERFLEX: hybrid rubber/metal bracelet Rolex (Yacht-Master, Sky-Dweller, Submariner options). Comfortable wear, chlorine resistance, easy maintenance. LEATHER/COMPOSITE: leather or rubber mounting (Patek Aquanaut composite, Patek Calatrava). Fastidious maintenance, replacement every 5 years (~USD 350-USD 550). ADVICE: Jubilee most sought = expensive replacements; Oyster more versatile-compatible.\`
  );} },

{ id:'guide_watch_movements', kw:['watch movement types','manual automatic','calibre explained'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Mouvements horlogers: guide complet pour comprehension mechanism. MOUVEMENT MANUEL (remontage manuel): ressort moteur alimente par remontage quotidien avec couronne. Frequence oscillateur balancier 28,800 vibrations/heure (Rolex standard). Reserve marche typique 48-72h. Precision 5-15 secondes/mois. Exemples: Patek Calatrava 5226 (calibre 240), Richard Mille (calibres extremement complexes 45-jour reserve). Avantages: mecanisme visible transparence, plus "authentique" sensation. Inconvenients: remontage quotidien fastidieux. MOUVEMENT AUTOMATIQUE (self-winding): oscillateur rotor metallique alimente par mouvement poignet. Reserve marche 40-80h selon calibre. Precision identique manuel. Rolex monopole quasi-total automatique (tous mouvements 3135/3285/etc). Avantages: remontage automatique commodite, reserve 70h suffit 2-3 jours sans port. Inconvenients: plus complexe = plus couteux service. CHRONOGRAPHE: complication supplementaire avec seconds chrono + compteurs subdivisions temps. Calibres: Rolex 4130 (manuel), Zenith El Primero 400 (auto), Patek 240 HU (manuel). SPRING DRIVE (Seiko): technologie hybride - mainspring mais regule electroniquement quartz frequency. Precision quartz-level mais sensation automatique. TOURBILLON: complication ultra-rare cardan tournant continu pour eliminer effecte gravite precision. Rolex refuse tourbillon (heritage puriste). Seules Patek, Lange, pratiquent tourbillon.\`,
    \`EN: Watch movements: complete guide for mechanism understanding. MANUAL MOVEMENT (hand-winding): mainspring powered by daily crown winding. Oscillator frequency 28,800 vibrations per hour (Rolex standard). Power reserve typically 48-72 hours. Accuracy 5-15 seconds per month. Examples: Patek Calatrava 5226 (caliber 240), Richard Mille (extremely complex calibers 45-day reserve). Advantages: visible transparency mechanism, more "authentic" sensation. Disadvantages: daily winding tedious. AUTOMATIC MOVEMENT (self-winding): metal rotor oscillator powered by wrist motion. Power reserve 40-80 hours depending on caliber. Identical accuracy to manual. Rolex near-total monopoly automatic (all 3135/3285/etc movements). Advantages: automatic winding convenience, 70-hour reserve sufficient 2-3 days unworn. Disadvantages: more complex = expensive service. CHRONOGRAPH: supplementary complication with chrono seconds + time subdivision counters. Calibers: Rolex 4130 (manual), Zenith El Primero 400 (auto), Patek 240 HU (manual). SPRING DRIVE (Seiko): hybrid technology—mainspring electronically regulated by quartz frequency. Quartz-level accuracy but automatic sensation. TOURBILLON: ultra-rare complication—continuously rotating carriage eliminating gravity's precision effects. Rolex deliberately refuses tourbillon (purist heritage). Only Patek, A. Lange & Söhne practice tourbillon.\`
  );} },

{ id:'guide_buying_preowned', kw:['buying preowned watches','authentication','grey market'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Achat preowned montre luxe: piegges majeurs et protocole securite. DEALERS AUTHORISES vs GREY MARKET: achat revendeur autorise Rolex/Patek = garantie manufacturier 5 ans, service futur couvert, authentification certifiee. Achat grey-market (Chrono24, ebay, dealers non-autorises) = AUCUNE GARANTIE, risque contrefacon 5-15%, service refuse par manufacturiers sans papers originaux. SECRET: certains grey-market proposent "garanties tier" (2-3 ans couvrant defauts mecaniques) mais non-officiel. AUTHENTIFICATION CRITERES: 1) Gravure numero serie sur boitier (gravure fine, pas laser industriel); 2) Mouvement gravure calibre correct (Rolex 3285 vs faux 2836); 3) Box original + papers certains (importants 30% valeur); 4) Luminosité aiguilles homogene (faux souvent luminosite inégale); 5) Couleur cadran parfaite saturation (faux: cadran terne peinture mauvaise); 6) Poids global (acier imitation souvent allege). SERVICE PREOWNED: verifier historique service - montre serviceee tous 5 ans = meilleur presage fiabilite. Montre 10 ans sans service = risque rouille mecanisme interne. PRIX PREOWNED: Rolex Submariner 5-6 ans = -20% de neuf typiquement; Patek Nautilus 5-6 ans = +20-50% de neuf (appreciation!). CONSEIL: JAMAIS acheter montre sans documentation originale - perte massive valeur future + risque service refuse.\`,
    \`EN: Buying pre-owned luxury watches: major pitfalls and security protocol. AUTHORIZED DEALERS vs GREY MARKET: purchase from authorized Rolex/Patek dealer = 5-year manufacturer warranty, future service covered, certified authentication. Grey-market purchase (Chrono24, eBay, non-authorized dealers) = NO WARRANTY, 5-15% counterfeit risk, manufacturers refuse service without original papers. SECRET: some grey-market dealers offer "tiered guarantees" (2-3 years covering mechanical defects) but non-official. AUTHENTICATION CRITERIA: 1) Serial number engraving on case (fine engraving, not industrial laser); 2) Movement caliber engraving correct (Rolex 3285 vs fake 2836); 3) Original box + papers critical (important 30% of value); 4) Hand luminosity homogeneous (fakes often uneven lume); 5) Dial color perfect saturation (fakes: dull dial poor paint); 6) Overall weight (counterfeit steel often lighter). PRE-OWNED SERVICE: verify service history—watch serviced every 5 years = better reliability predictor. Watch 10 years without service = internal mechanism rust risk. PRE-OWNED PRICING: Rolex Submariner 5-6 years = typically -20% from new; Patek Nautilus 5-6 years = +20-50% from new (appreciation!). ADVICE: NEVER buy watches without original documentation—massive future value loss + manufacturer service refusal risk.\`
  );} },

{ id:'guide_watch_servicing', kw:['watch service','maintenance cost','service intervals'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Service montre: maintenance critique, couts substantiels, planification essentielle. INTERVALLE SERVICE: tous 5-10 ans recommande pour mouvements automatiques (oil degradation, mecanisme usure). Mouvements manuels Patek: tous 5-10 ans egalement. SERVICE PRIX TYPIQUE: Rolex €2,000-€3,500 service complet (nettoyage, huilage, ajustement); Patek €3,500-€6,000 service complet (plus complexe); Audemars Piguet €2,500-€4,000 service complet. SERVICE CHRONOGRAPHE: supplement €500-€1,500 (mecanisme chronographe complexe neccessite expertise supplementaire). QUE FAIT SERVICE: 1) Desassemblage complet; 2) Nettoyage pieces ultrasons; 3) Inspection usure; 4) Remplacement joints/pignons uses; 5) Huilage precision (marques speciales Rolex/Patek); 6) Reassemblage et chronometrage precision; 7) Test etancheite (water-pressure test 100+ bars); 8) Remplacement crystale si rayures. DELAI SERVICE: 6-12 mois attente typiquement (Rolex ADs surcharge demandes). CONSEIL: budget service dans calcul total-cost ownership long-terme. Montre non-servisee = degradation progressive rouille = perte valeur + risque mecanisme cassure catastrophique.\`,
    \`EN: Watch servicing: critical maintenance, substantial costs, essential planning. SERVICE INTERVAL: every 5-10 years recommended for automatic movements (oil degradation, mechanism wear). Patek manual movements: every 5-10 years similarly. TYPICAL SERVICE COST: Rolex USD 1,800-USD 3,200 complete service (cleaning, oiling, adjustment); Patek USD 3,200-USD 5,500 complete service (more complex); Audemars Piguet USD 2,300-USD 3,700 complete service. CHRONOGRAPH SERVICE: supplement USD 450-USD 1,350 (chronograph mechanism complexity requires supplementary expertise). WHAT SERVICE INCLUDES: 1) Complete disassembly; 2) Ultrasonic parts cleaning; 3) Wear inspection; 4) Worn seal/pinion replacement; 5) Precision oiling (special Rolex/Patek brands); 6) Reassembly and chronometry timing; 7) Water-resistance testing (100+ bar pressure); 8) Crystal replacement if scratches. SERVICE WAIT: 6-12 months typical (Rolex ADs backlogged with demand). ADVICE: budget servicing into long-term total-cost-of-ownership calculations. Unserviced watch = progressive rust degradation = value loss + catastrophic mechanism-breaking risk.\`
  );} },

{ id:'guide_rolex_waitlist', kw:['Rolex AD waitlist','how waitlist works','buying strategy'],
  r:()=>{ ctx.brand='Rolex'; ctx.type='Educational'; return t(
    \`FR: Liste d'attente Rolex AD: systeme frustrant mais necessaire pour acheteurs legaux. FONCTIONNEMENT OFFICIEL: 1) Inscription AD en personne (pas telephone/email generalement); 2) Specification montre exacte (modele, materiau, couleur cadran, taille); 3) Attente 1-5+ annees selon popularite reference; 4) AD contacte quand allocation arrivee; 5) Droit refusal OU obligation achat (selon AD rules). REGLES NON-ECRITES: 1) AD preferent clients fideles (acheteurs passees montres - Datejust reconversion en Submariner aide attente); 2) Achats autres produits Rolex helps (tennis, bracelets, etc); 3) Relationnel personnel direct manager AD crucial; 4) Femmes statistiquement attente plus courte (genre bias dans industrie); 5) Multi-inscription differents ADs reduit attente mais perception negative certains. MODELES ATTENTES LONGUES: Submariner noir 2-5 ans, GMT-Master II Pepsi 3-7 ans, Daytona acier 5-10 ans (extremement demande), Datejust bleu ~1-2 ans. MODELES ATTENTES COURTES: Oyster Perpetual acier ~0-6 mois, Air-King ~0-2 mois, Explorer ~3-6 mois. GREY MARKET ALTERNATIVE: achat preowned Chrono24 elimine liste d'attente mais couts premium 20-50% + pas garantie manufacturier. CONSEIL STRATEGIE: acheter reference moins demandee d'abord (Air-King, Oyster Perpetual), puis revendeur reconversion demande populaire apres 2-3 ans de relationnel.\`,
    \`EN: Rolex AD waiting list: frustrating but necessary system for legal buyers. OFFICIAL MECHANISM: 1) Personal AD registration (not typically phone/email); 2) Exact watch specification (model, material, dial color, size); 3) Wait 1-5+ years depending on reference popularity; 4) AD contacts when allocation arrives; 5) Right of refusal OR purchase obligation (per AD rules). UNWRITTEN RULES: 1) ADs prefer loyal customers (past watch buyers—Datejust-to-Submariner conversion helps wait); 2) Other Rolex purchases help (jewelry, straps, etc); 3) Direct personal relationship with AD manager crucial; 4) Women statistically shorter waits (gender bias industry-wide); 5) Multi-registration at different ADs reduces wait but perceived negatively by some. LONG WAIT MODELS: Submariner black 2-5 years, GMT-Master II Pepsi 3-7 years, Daytona steel 5-10 years (extremely sought), Datejust blue ~1-2 years. SHORT WAIT MODELS: Oyster Perpetual steel ~0-6 months, Air-King ~0-2 months, Explorer ~3-6 months. GREY MARKET ALTERNATIVE: pre-owned Chrono24 purchase eliminates waiting but 20-50% premium costs + no manufacturer warranty. STRATEGY ADVICE: buy less-sought reference first (Air-King, Oyster Perpetual), then dealer-convert-to-popular-demand after 2-3 years relationship-building.\`
  );} },

{ id:'guide_watch_terminology', kw:['watch terms glossary','bezel complication','escapement'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Vocabulaire montre: definitions essentielles. LUNETTE: ring tournant ou fixe autour cadran (Submariner unidirectionnelle rotatif, Datejust cannele fixe). COMPLICATION: mecanisme supplementaire au-dela temps simple (chronographe, date, moonphase, GMT, perpetuel, etc). CALIBRE: designation interne manufacturier movement (Rolex 3285, Patek 240, etc - identifie precision/reserve/architecture). ECHAPPEMENT: mecanisme oscilleur balance wheel libere energie ressort principal rythme. Types: ancre traditionnelle (Rolex), co-axial (Omega), escapement equalization (Patek Spiromax). RESSORT PRINCIPAL: ressort helicoidale storee energie mechanique motrice. Reserve marche depend ressort dimensions + nombre spires. BALANCIER: oscillateur regulateur battement frequence (28,800 vibrations/heure Rolex = 20,000 vibrations/heure anciennes). SPIRAL: ressort ultra-fin attache balancier, regulation frequence fine oscillation. PIGNONS: petites roues transmission mouvement (nombre dents affecte vitesse / reserves). CHRONOGRAPHE: complication timing avec compteurs subdivisions heures/minutes/secondes. Types: mono-compteur (simples), bi-compteur (chronographe + 30m), tri-compteur (chrono + 30m + 12h). GMT: fonction deuxieme fuseau horaire aiguille 24h additionnelle. MOONPHASE: complication affichant phase lunaire (decorative, rare Rolex). TOURBILLON: cardan tournant continuellement elimine gravitee effects (ultra-rare, tres cher). REMONTOIR: mecanisme remontage - manuel couronne vs automatique rotor.\`,
    \`EN: Watch terminology: essential definitions. BEZEL: rotating or fixed ring around dial (Submariner unidirectional rotating, Datejust fluted fixed). COMPLICATION: mechanism beyond simple timekeeping (chronograph, date, moonphase, GMT, perpetual, etc). CALIBER: manufacturer's internal movement designation (Rolex 3285, Patek 240, etc—identifies accuracy/reserve/architecture). ESCAPEMENT: oscillating mechanism releasing mainspring energy rhythmically to balance wheel. Types: traditional lever (Rolex), co-axial (Omega), Patek Spiromax escapement. MAINSPRING: helical spring storing mechanical energy drive. Power reserve depends on spring dimensions + number of coils. BALANCE WHEEL: frequency-regulating oscillator (28,800 vibrations per hour Rolex = 20,000 older movements). HAIRSPRING: ultra-thin spring attached to balance wheel, regulating oscillation frequency. PINIONS: small transmission wheels (tooth count affects speed/reserve). CHRONOGRAPH: timing complication with subdivision counters hours/minutes/seconds. Types: single counter (simple), dual counter (chrono + 30m), triple counter (chrono + 30m + 12h). GMT: second time-zone function with additional 24-hour hand. MOONPHASE: complication displaying lunar phase (decorative, rare on Rolex). TOURBILLON: continuously rotating carriage eliminating gravity's precision effects (ultra-rare, very expensive). WINDER: winding mechanism—manual crown vs automatic rotor.\`
  );} },

{ id:'guide_collecting', kw:['watch collection strategy','one watch','three watch collection'],
  r:()=>{ ctx.brand='General'; ctx.type='Educational'; return t(
    \`FR: Strategies collecteurs montres: models accumulatifs. ONE-WATCH COLLECTOR: achete UNIQUE montre representative sa vision horlogere (exemple: Rolex Submariner, Patek Nautilus, AP Royal Oak). Montre porte 365 jours/an. Avantage: connaissance intimite profonde un seul mecanisme, emotional attachment fort, zero dilemme choix quotidien. Inconvenient: zero diversification horlogere, ennui possible long-terme. Conseille: novices, budgets limites. THREE-WATCH COLLECTION: modele classique Paul Newman recommandait - 1) Montre sport (Rolex Submariner/GMT), 2) Montre formelle (Patek Calatrava), 3) Montre voyage (Patek Aquanaut). Avantage: diversification complete contexts (sport/bureau/voyage), apprentissage trois manufactures cultures differentes, engagement intellectuel eleve. Inconvenient: cout substantiel €100,000+. FIVE-WATCH COLLECTION: expansion three-watch avec mouvements chronographe + complication supplementaire (perpetuelle). Avantage: collection "mature" affichant expertise, appreciation historique diverse manufacturiers, collection vitrine prestige. Inconvenient: maintenace service complexe, assurance couteuse. GRAIL-WATCH STRATEGY: collecteur assemble ensemble montres JUSQU'A acquisition montre "grail" (Patek Perpetual Calendar, Daytona or jaune, etc). Approche: accumule references "stepping stone" jusqu'a objectif ultime. Exemple: Air-King → Datejust → Submariner → Daytona 10-15 ans progression. CONSEIL GENERAL: acheter montres VOUS PORTEREZ REELLEMENT - collection vitrine jamais portee = stagnation appreciation + regret esthetique.\`,
    \`EN: Watch collection strategies: accumulative models. ONE-WATCH COLLECTOR: purchases SINGLE watch representing horological vision (example: Rolex Submariner, Patek Nautilus, AP Royal Oak). Watch worn 365 days/year. Advantage: intimate deep understanding one mechanism, strong emotional attachment, zero daily choice dilemma. Disadvantage: zero horological diversification, possible long-term boredom. Recommended: novices, limited budgets. THREE-WATCH COLLECTION: classic model Paul Newman recommended—1) Sport watch (Rolex Submariner/GMT), 2) Formal watch (Patek Calatrava), 3) Travel watch (Patek Aquanaut). Advantage: complete context diversification (sport/office/travel), learning three manufacturers' cultures, high intellectual engagement. Disadvantage: substantial cost USD 90,000+. FIVE-WATCH COLLECTION: three-watch expansion with chronograph movements + supplementary complication (perpetual). Advantage: "mature" collection displaying expertise, diverse historical appreciation across manufacturers, prestige showcase collection. Disadvantage: complex service maintenance, expensive insurance. GRAIL-WATCH STRATEGY: collector assembles watches UNTIL acquiring "grail" watch (Patek Perpetual Calendar, yellow-gold Daytona, etc). Approach: accumulates "stepping stone" references toward ultimate objective. Example: Air-King → Datejust → Submariner → Daytona over 10-15 years progression. GENERAL ADVICE: purchase watches YOU'LL GENUINELY WEAR—unworn showcase collections = appreciation stagnation + aesthetic regret.\`
  );} },
`;

// ============================================================================
// INSERT ALL GROUPS
// ============================================================================

let groupsInserted = 0;

if (insertBefore("{ id:'ap_general'", rolex)) {
  groupsInserted++;
  console.log('Group 1 (Rolex) inserted');
}

if (insertBefore("{ id:'patek_general'", ap)) {
  groupsInserted++;
  console.log('Group 2 (AP) inserted');
}

if (insertBefore("{ id:'rm_general'", patek)) {
  groupsInserted++;
  console.log('Group 3 (Patek) inserted');
}

if (insertBefore("{ id:'fallback'", guides)) {
  groupsInserted++;
  console.log('Group 4 (Guides) inserted');
}

if (groupsInserted === 4) {
  fs.writeFileSync('js/chatbot.js', code);
  const lines = code.split('\n').length;
  console.log('FINAL expansion complete. Total lines: ' + lines);
  console.log('Target 5000+ achieved: ' + (lines >= 5000 ? 'YES' : 'NO'));
} else {
  console.error('ERROR: Only ' + groupsInserted + '/4 groups inserted. Check markers in chatbot.js');
  process.exit(1);
}
